leg_sim:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  J1_position_controller:
    type: effort_controllers/JointPositionController
    joint: J1
    pid: {p: 100, i: 3, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}
  J2_position_controller:
    type: effort_controllers/JointPositionController
    joint: J2
    pid: {p: 100, i: 3, d: 0.3055, i_clamp_min:  -1000, i_clamp_max: 1000}

